#!/bin/ash
echo "start " >filebrowser.log
model=$(cat /proc/xiaoqiang/model)
setconfig model $model
port=$(getconfig port)
if [[ -z "$port" ]]; then
	#statements
	port=8088
	setconfig port $port
fi


filebrowser='/bin/filebrowser'
xq=$(cat /proc/xiaoqiang/model)
if [ "$xq" == "R1D" -o "$xq" == "R2D" -o "$xq" == "R3D"  ]; then
	filebrowser='/bin/filebrowser'
elif [ "$xq" == "R3" -o "$xq" == "R3P" -o "$xq" == "R3G" -o "$xq" == "R1CM" ]; then
	filebrowser='/bin/filebrowser_mips'
fi
#start filebrowser
echo "start $filebrowser with port: $port" >>filebrowser.log
$filebrowser -c /etc/filebrowser.json -p $port /dev/null 2>&1

PID=$(ps|grep $filebrowser |grep -v grep|awk '{print $1}')
echo "pid of filebrowser: $PID" >>filebrowser.log

#setconfig enable on
enable="on"
echo "start while" >>filebrowser.log
while [[ "$enable" == "on" ]]; do
	#statements
	enable=$(getconfig enable)
	if [[ -z "$port" ]]; then
	    setconfig enable on   
	fi
	echo "enable: $enable" >>filebrowser.log
	sleep 3
done
echo "end while" >> filebrowser.log

echo "pid of filebrowser to kill: $PID" >>filebrowser.log
kill $PID 
/bin/killall $filebrowser

echo "end kill" >>filebrowser.log 

echo "pid of $$ startFileBrowser to kill" >>filebrowser.log 
kill $$                           
echo "stopFileBrowser" >> filebrowser.log
#exit 0
